[github.com/lhxlnsy/pap-go-server]2022/03/04 - 10:19:23.259	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_initdb.go:34	自动创建数据库失败!	{"error": "ERROR: syntax error at or near \"-\" (SQLSTATE 42601)"}
[github.com/lhxlnsy/pap-go-server]2022/03/04 - 10:19:40.176	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_initdb.go:34	自动创建数据库失败!	{"error": "ERROR: syntax error at or near \"-\" (SQLSTATE 42601)"}
[github.com/lhxlnsy/pap-go-server]2022/03/04 - 10:19:52.154	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_initdb.go:34	自动创建数据库失败!	{"error": "open config.yaml: permission denied"}
[github.com/lhxlnsy/pap-go-server]2022/03/04 - 10:21:12.812	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_initdb.go:23	已存在数据库配置!
[github.com/lhxlnsy/pap-go-server]2022/03/04 - 10:22:05.176	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_initdb.go:23	已存在数据库配置!
[github.com/lhxlnsy/pap-go-server]2022/03/04 - 10:24:42.320	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/03/04 - 10:25:13.789	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_initdb.go:34	自动创建数据库失败!	{"error": "ERROR: database \"papadmin\" already exists (SQLSTATE 42P04)"}
[github.com/lhxlnsy/pap-go-server]2022/03/04 - 10:25:49.608	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:35	登陆失败! 用户名不存在或者密码错误!	{"error": "db not init"}
[github.com/lhxlnsy/pap-go-server]2022/03/04 - 10:28:09.006	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 09:07:48.290	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 09:15:48.126	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:00:29.790	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:01:39.582	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:12:04.396	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:15:10.730	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:16:40.322	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:18:04.251	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:18:25.032	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:18:29.617	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:18:30.574	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:18:56.313	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:28:32.999	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:28:55.888	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:29:04.651	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:29:11.369	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:29:28.671	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:31:41.370	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:31:58.206	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:33:17.339	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:33:42.527	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:34:23.580	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:37:25.974	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:37:32.500	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:38:00.090	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:39:17.549	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:42:18.244	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:44:09.231	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:44:30.656	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:54:50.860	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:55:00.097	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:55:59.899	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:56:06.792	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:58:14.362	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:58:20.754	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:59:42.336	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/07 - 10:59:52.861	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/10 - 11:09:10.478	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/10 - 11:09:20.224	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/10 - 11:09:27.998	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/10 - 11:10:25.467	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/10 - 11:10:26.850	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/10 - 11:10:30.624	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/10 - 11:10:31.391	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/10 - 11:10:31.607	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/10 - 11:10:31.816	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/10 - 11:11:59.874	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/03/10 - 11:12:04.941	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/10 - 11:12:34.681	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/10 - 11:12:38.361	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/10 - 11:12:39.414	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/10 - 11:12:39.918	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/10 - 11:12:40.151	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/10 - 11:13:20.690	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/03/15 - 11:30:09.639	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/03/31 - 09:08:12.872	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/31 - 09:08:17.770	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/31 - 09:08:24.087	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/03/31 - 09:08:25.683	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 09:47:51.147	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 09:48:09.434	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 09:48:53.465	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 09:50:16.038	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 09:50:18.027	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 09:51:21.415	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 10:18:42.353	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 11:19:31.571	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 11:22:02.226	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 11:24:46.802	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 11:33:56.511	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 11:37:56.158	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 11:38:35.182	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 11:41:48.157	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 11:44:39.377	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/pap/pap_siteinfor.go:129	获取失败!	{"error": "ERROR: relation \"site_information\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 12:09:40.689	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 12:09:53.869	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/pap/pap_siteinfor.go:129	获取失败!	{"error": "ERROR: relation \"site_information\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 12:10:30.497	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 12:10:36.435	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/pap/pap_siteinfor.go:130	获取失败!	{"error": "ERROR: relation \"site_information\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 12:11:17.537	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 12:11:23.871	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/pap/pap_siteinfor.go:131	获取失败!	{"error": "ERROR: relation \"site_information\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 12:12:27.328	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 12:12:30.683	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/pap/pap_siteinfor.go:134	获取失败!	{"error": "ERROR: relation \"site_information\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 12:12:54.912	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 12:13:00.686	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/pap/pap_siteinfor.go:134	获取失败!	{"error": "ERROR: relation \"site_information\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 12:14:18.821	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/pap/pap_siteinfor.go:134	获取失败!	{"error": "ERROR: relation \"site_information\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 12:14:22.048	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 12:31:54.683	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 12:47:43.575	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 12:47:59.683	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/pap/pap_siteinfor.go:134	获取失败!	{"error": "ERROR: relation \"site_information\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 12:50:42.102	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 12:50:54.107	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/pap/pap_siteinfor.go:134	获取失败!	{"error": "ERROR: relation \"site_information\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 12:51:57.253	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 12:58:42.329	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/pap/pap_siteinfor.go:134	获取失败!	{"error": "unsupported data type: 0xc001426360: Table not set, please set it like: db.Model(&user) or db.Table(\"users\")"}
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 12:59:16.979	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 12:59:23.491	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 12:59:34.723	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 13:05:48.400	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 13:06:44.752	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 13:07:14.416	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 13:07:18.527	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/pap/pap_siteinfor.go:134	获取失败!	{"error": "ERROR: column site_information.deleted_at does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 13:09:30.239	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 13:09:36.670	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/pap/pap_siteinfor.go:134	获取失败!	{"error": "ERROR: column site_information.deleted_at does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 13:09:53.044	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/pap/pap_siteinfor.go:134	获取失败!	{"error": "ERROR: column site_information.deleted_at does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 13:10:23.919	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 13:10:30.281	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/pap/pap_siteinfor.go:129	获取失败!	{"error": "ERROR: column site_information.deleted_at does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 13:13:01.850	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/api/v1/pap/pap_siteinfor.go:129	获取失败!	{"error": "ERROR: column site_information.deleted_at does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 13:13:05.422	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 13:13:40.558	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 13:15:09.501	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/04 - 13:21:51.371	[31merror[0m	/home/jeffrey/Dropbox/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/05 - 12:02:27.654	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/05 - 12:05:20.738	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/05 - 12:06:35.407	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/05 - 12:14:23.890	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/05 - 12:15:20.273	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/05 - 12:17:31.167	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/05 - 12:18:07.534	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/05 - 12:19:05.917	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/05 - 12:19:32.989	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/05 - 12:20:43.148	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/05 - 12:24:19.962	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/05 - 12:37:56.867	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/12 - 10:07:00.270	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/12 - 10:09:02.764	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/13 - 10:28:21.905	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/13 - 10:28:37.137	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/13 - 10:31:25.392	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/13 - 10:47:42.986	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/13 - 11:01:27.333	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/13 - 11:29:16.921	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/13 - 11:35:57.014	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/13 - 11:37:09.510	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/13 - 11:42:01.444	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/13 - 11:42:25.012	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/13 - 11:48:29.409	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/13 - 11:51:06.400	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/13 - 11:51:48.592	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/13 - 11:52:28.496	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/13 - 11:54:05.040	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/13 - 11:55:17.487	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/13 - 12:00:41.438	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/13 - 12:01:45.454	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/13 - 12:03:29.405	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/13 - 12:04:10.364	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/13 - 13:45:05.897	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/13 - 13:48:30.549	[31merror[0m	/mnt/data2/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/19 - 13:40:48.828	[31merror[0m	/mnt/data/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/04/20 - 10:57:37.916	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	net.Listen error: listen tcp :8888: bind: address already in use
[github.com/lhxlnsy/pap-go-server]2022/04/20 - 11:21:36.152	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	net.Listen error: listen tcp :8888: bind: address already in use
[github.com/lhxlnsy/pap-go-server]2022/04/20 - 13:34:45.809	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/20 - 13:34:45.992	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/22 - 11:37:34.368	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/22 - 11:39:07.872	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/22 - 11:41:53.760	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/22 - 11:45:38.865	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/22 - 11:50:45.953	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/22 - 12:40:04.484	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:194	获取失败	{"error": "ERROR: OFFSET must not be negative (SQLSTATE 2201X)"}
[github.com/lhxlnsy/pap-go-server]2022/04/22 - 12:40:43.617	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:194	获取失败	{"error": "ERROR: OFFSET must not be negative (SQLSTATE 2201X)"}
[github.com/lhxlnsy/pap-go-server]2022/04/22 - 12:40:53.840	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:194	获取失败	{"error": "ERROR: OFFSET must not be negative (SQLSTATE 2201X)"}
[github.com/lhxlnsy/pap-go-server]2022/04/22 - 12:45:52.627	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/04/27 - 10:31:27.955	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/03 - 11:00:34.593	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/03 - 11:01:47.185	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/03 - 11:04:26.625	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/03 - 11:06:37.666	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/03 - 11:08:26.338	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/03 - 11:12:50.162	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/03 - 11:16:20.274	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/03 - 11:16:24.725	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:237	获取失败	{"error": "redis: can't unmarshal *map[string]interface {} (consider implementing BinaryUnmarshaler)"}
[github.com/lhxlnsy/pap-go-server]2022/05/03 - 11:16:52.656	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:237	获取失败	{"error": "redis: can't unmarshal *map[string]interface {} (consider implementing BinaryUnmarshaler)"}
[github.com/lhxlnsy/pap-go-server]2022/05/03 - 11:19:35.330	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/03 - 11:21:01.587	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/03 - 11:21:25.171	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/03 - 11:21:51.346	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/03 - 11:23:21.171	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/03 - 11:23:46.514	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/03 - 11:32:36.515	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/03 - 11:33:22.083	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/04 - 11:25:47.434	[31merror[0m	/mnt/data/pap-go-server/core/server.go:47	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/04 - 11:30:50.891	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/04 - 11:45:01.419	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/04 - 11:49:02.204	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/04 - 11:49:50.523	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/04 - 11:54:55.356	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/04 - 11:56:43.036	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/04 - 11:56:52.492	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/04 - 12:00:06.412	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/04 - 12:02:45.676	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/04 - 12:03:50.988	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/04 - 12:04:36.876	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/04 - 12:08:24.300	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/04 - 12:10:41.948	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/04 - 12:21:22.301	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/04 - 12:21:34.238	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/04 - 12:25:53.789	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/04 - 12:27:01.229	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/04 - 12:31:51.261	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/05 - 09:14:02.123	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/05 - 09:14:50.523	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/09 - 12:05:40.610	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/09 - 12:06:00.376	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:131	获取失败!	{"error": "ERROR: column \"error_code_status.error_source\" must appear in the GROUP BY clause or be used in an aggregate function (SQLSTATE 42803)"}
[github.com/lhxlnsy/pap-go-server]2022/05/09 - 12:06:27.874	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/09 - 12:15:01.618	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 11:33:53.432	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:06:42.585	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:08:21.977	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:12:28.074	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:14:09.371	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:15:21.674	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:17:12.282	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:22:20.986	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:22:30.394	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:25:20.588	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:25:47.755	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:37:25.004	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:40:25.291	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:41:05.611	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:41:23.404	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:44:41.467	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:45:25.915	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:46:03.243	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:46:22.939	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:46:42.155	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:48:01.643	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:48:19.515	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:48:49.819	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:49:26.363	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:49:59.100	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:51:52.844	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:53:55.308	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:55:58.060	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:57:08.716	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/10 - 12:57:48.204	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:11:31.816	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:11:31.820	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:147	获取失败	{"error": "ERROR: relation \"PAPSolar\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:11:31.821	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:215	获取失败	{"error": "ERROR: relation \"PAPSolar\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:24:10.111	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:147	获取失败	{"error": "ERROR: relation \"PAPSolar\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:24:10.111	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:215	获取失败	{"error": "ERROR: relation \"PAPSolar\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:24:27.281	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:147	获取失败	{"error": "ERROR: relation \"PAPSolar\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:24:27.283	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:215	获取失败	{"error": "ERROR: relation \"PAPSolar\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:25:13.423	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:147	获取失败	{"error": "ERROR: relation \"PAPSolar\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:25:13.425	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:215	获取失败	{"error": "ERROR: relation \"PAPSolar\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:34:24.053	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:34:39.136	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:147	获取失败	{"error": "ERROR: relation \"PAPSolar_1010\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:34:39.140	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:215	获取失败	{"error": "ERROR: relation \"PAPSolar\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:35:01.925	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:35:06.324	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:215	获取失败	{"error": "ERROR: relation \"PAPSolar\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:35:06.326	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:147	获取失败	{"error": "ERROR: column pap.Inst A-Phase Current does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:35:39.493	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:35:43.761	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:215	获取失败	{"error": "ERROR: relation \"PAPSolar\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:42:27.317	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:42:33.272	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:215	获取失败	{"error": "ERROR: syntax error at or near \"from\" (SQLSTATE 42601)"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:42:45.045	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:47:25.333	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:49:44.645	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:50:55.221	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:51:08.463	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:51:14.810	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 10:52:18.235	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 11:01:45.623	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 11:04:34.652	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 11:04:51.660	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 11:05:21.619	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 11:05:28.795	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 11:06:05.292	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 11:06:22.791	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 11:08:45.252	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 11:09:09.347	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 11:10:46.425	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 11:10:55.288	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 11:12:01.620	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 11:12:45.989	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 11:13:13.228	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 11:13:37.933	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 11:18:29.546	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 11:19:09.889	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 11:19:40.394	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 11:19:40.401	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:147	获取失败	{"error": "ERROR: relation \"PAPSolar_EEMS_99999\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 11:24:10.782	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 11:24:26.637	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 11:26:38.135	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 11:26:59.549	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:235	获取失败	{"error": "redis: nil"}
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 11:28:03.910	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/11 - 11:32:07.782	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 10:13:24.828	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: relation \"PAPSolar\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 10:19:32.709	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: relation \"PAPSolar\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 10:19:59.265	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: relation \"PAPSolar\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 10:23:21.889	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: relation \"PAPSolar\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 10:25:07.668	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: relation \"PAPSolar\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 10:25:21.873	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: relation \"PAPSolar\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 10:29:14.532	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: relation \"PAPSolar\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 10:30:12.887	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: relation \"PAPSolar\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 10:54:54.092	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: relation \"PAPSolar\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 10:58:38.583	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 10:58:45.125	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: relation \"PAPSolar_EEMS_EEMS_1010\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 10:59:06.695	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 10:59:10.636	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: column \"Inst A-Phase Voltage\" does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 10:59:34.679	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:03:18.721	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: column \"Inst A-Phase Voltage\" does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:03:48.968	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: column \"Inst A-Phase Voltage\" does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:04:20.789	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: column \"Inst A-Phase Voltage\" does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:04:41.675	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: column \"Inst A-Phase Voltage\" does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:05:27.324	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: column \"Inst A-Phase Voltage\" does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:08:20.007	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:08:24.371	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: column \"Inst A-Phase Voltage\" does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:09:25.655	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:09:30.281	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: column \"Inst A-Phase Voltage\" does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:13:14.967	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:13:20.254	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: column \"Inst A-Phase Voltage\" does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:13:45.143	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:13:49.025	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: column \"Inst A-Phase Voltage\" does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:16:12.423	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:16:17.093	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: column \"Inst A-Phase Voltage\" does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:17:31.479	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:17:35.897	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: column \"Inst A-Phase Voltage\" does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:17:46.887	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:17:52.772	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: column \"Inst A-Phase Voltage\" does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:18:08.871	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:18:13.522	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: column \"Inst A-Phase Voltage\" does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:19:12.919	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:19:16.338	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: column \"Inst A-Phase Voltage\" does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:26:03.511	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:26:10.151	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: column \"Site Code\" does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:26:39.655	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:26:51.548	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: column \"Site Code\" does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:27:07.511	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:27:10.704	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: column \"pap.DeviceID\" must appear in the GROUP BY clause or be used in an aggregate function (SQLSTATE 42803)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:27:22.535	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:27:25.714	[31merror[0m	/mnt/data/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: column \"pap.DeviceDesc\" must appear in the GROUP BY clause or be used in an aggregate function (SQLSTATE 42803)"}
[github.com/lhxlnsy/pap-go-server]2022/05/12 - 11:27:48.823	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/17 - 09:27:49.059	[31merror[0m	/mnt/data/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/23 - 10:03:26.784	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "db not init"}
[github.com/lhxlnsy/pap-go-server]2022/05/23 - 10:03:34.235	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "db not init"}
[github.com/lhxlnsy/pap-go-server]2022/05/23 - 10:03:37.390	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "db not init"}
[github.com/lhxlnsy/pap-go-server]2022/05/23 - 10:04:51.153	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "db not init"}
[github.com/lhxlnsy/pap-go-server]2022/05/23 - 10:04:57.234	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "db not init"}
[github.com/lhxlnsy/pap-go-server]2022/05/23 - 10:05:11.894	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/23 - 10:15:40.103	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/23 - 11:45:11.110	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: invalid input syntax for type interval: \"\" (SQLSTATE 22007)"}
[github.com/lhxlnsy/pap-go-server]2022/05/23 - 11:47:30.161	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "ERROR: invalid input syntax for type interval: \"\" (SQLSTATE 22007)"}
[github.com/lhxlnsy/pap-go-server]2022/05/23 - 12:20:18.221	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/23 - 12:21:29.949	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/23 - 12:22:02.701	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/23 - 12:25:09.405	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/23 - 12:33:45.662	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/23 - 12:33:50.282	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "sql: no rows in result set"}
[github.com/lhxlnsy/pap-go-server]2022/05/23 - 12:34:18.886	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "sql: expected 5 destination arguments in Scan, not 1"}
[github.com/lhxlnsy/pap-go-server]2022/05/23 - 12:34:22.996	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:257	获取失败	{"error": "sql: expected 5 destination arguments in Scan, not 1"}
[github.com/lhxlnsy/pap-go-server]2022/05/23 - 12:36:10.750	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/23 - 12:37:31.774	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/23 - 12:46:51.662	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/23 - 12:47:37.630	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/23 - 12:48:26.606	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/23 - 12:51:15.486	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/24 - 12:18:49.893	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/30 - 13:08:38.788	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/30 - 13:25:07.167	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 08:58:21.055	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 09:17:44.480	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 09:23:50.688	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 09:24:23.672	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:51	创建失败!	{"error": "ERROR: duplicate key value violates unique constraint \"chart_saveds_chart_uuid_key\" (SQLSTATE 23505)"}
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 09:25:46.677	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:51	创建失败!	{"error": "ERROR: duplicate key value violates unique constraint \"chart_saveds_chart_uuid_key\" (SQLSTATE 23505)"}
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 09:26:13.024	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 09:26:37.478	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:51	创建失败!	{"error": "ERROR: duplicate key value violates unique constraint \"chart_saveds_chart_uuid_key\" (SQLSTATE 23505)"}
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 09:37:50.769	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 09:39:37.649	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 09:49:11.410	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 09:51:29.058	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 09:51:51.682	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 09:52:19.202	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 09:53:59.026	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 09:55:21.298	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 10:05:02.146	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 10:05:55.058	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 10:07:23.346	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 10:07:52.658	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 10:10:13.874	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 10:11:06.866	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 10:15:11.331	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 10:22:30.623	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:76	查询失败!	{"error": "ERROR: relation \"chart_saveds\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 10:22:39.043	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 10:48:44.539	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:309	获取失败	{"error": "ERROR: invalid input syntax for type interval: \"\" (SQLSTATE 22007)"}
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 10:49:15.431	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:309	获取失败	{"error": "ERROR: invalid input syntax for type interval: \"\" (SQLSTATE 22007)"}
[github.com/lhxlnsy/pap-go-server]2022/05/31 - 10:49:39.808	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:309	获取失败	{"error": "ERROR: invalid input syntax for type interval: \"\" (SQLSTATE 22007)"}
[github.com/lhxlnsy/pap-go-server]2022/06/02 - 12:04:09.239	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/06/02 - 12:37:34.852	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:103	删除失败!	{"error": "WHERE conditions required"}
[github.com/lhxlnsy/pap-go-server]2022/06/02 - 12:38:35.145	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/06/02 - 12:38:39.430	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:104	删除失败!	{"error": "WHERE conditions required"}
[github.com/lhxlnsy/pap-go-server]2022/06/02 - 12:39:15.897	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/06/02 - 12:39:23.808	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:104	删除失败!	{"error": "WHERE conditions required"}
[github.com/lhxlnsy/pap-go-server]2022/06/02 - 12:41:40.201	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/06/02 - 12:41:44.937	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:104	删除失败!	{"error": "ERROR: invalid input syntax for type bigint: \"1653960883901_admin\" (SQLSTATE 22P02)"}
[github.com/lhxlnsy/pap-go-server]2022/06/02 - 12:42:41.689	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/06/07 - 13:01:25.120	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/06/07 - 13:02:46.840	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:63	更新失败!	{"error": "unsupported data type: map[chart_stype_option = ?:{\"autoScale\":true,\"colorScheme\":\"cool\",\"legend\":true,\"animations\":true,\"xAxis\":true,\"yAxis\":true,\"showYAxisLabel\":true,\"showXAxisLabel\":true,\"xAxisLabel\":\"Time\",\"yAxisLabel\":\"Value\",\"timeline\":true,\"mutli\":[],\"calculated\":[{\"name\":\"Avg:Inst A-Phase Current\",\"value\":4987.7338354110725},{\"name\":\"Avg:Inst B-Phase Current\",\"value\":6082.118836212158},{\"name\":\"Avg:Inst C-Phase Current\",\"value\":5862.963732242586}],\"paddingBetweenBars\":\"8\",\"paddingBetweenGroups\":\"16\",\"view\":[1012,400],\"type\":\"Line Chart\",\"animation\":true}]: Table not set, please set it like: db.Model(&user) or db.Table(\"users\")"}
[github.com/lhxlnsy/pap-go-server]2022/06/07 - 13:04:08.960	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/06/07 - 13:04:15.269	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:63	更新失败!	{"error": "ERROR: column \"chart_stype_option = ?\" of relation \"chart_saveds\" does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/06/07 - 13:10:48.145	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/06/07 - 13:10:56.807	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:63	更新失败!	{"error": "ERROR: column \"chart_stype_option = ?\" of relation \"chart_saveds\" does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/06/07 - 13:11:14.752	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/06/07 - 13:11:18.398	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:63	更新失败!	{"error": "ERROR: column \"chart_stype_option = ?\" of relation \"chart_saveds\" does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/06/07 - 13:11:38.288	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/06/07 - 13:11:42.391	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:63	更新失败!	{"error": "ERROR: column \"chart_style_option = ?\" of relation \"chart_saveds\" does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/06/07 - 13:17:18.193	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/06/07 - 13:17:50.704	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:63	更新失败!	{"error": "ERROR: column \"chart_style_option = ?\" of relation \"chart_saveds\" does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/06/07 - 13:18:02.481	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/06/07 - 13:18:05.552	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:63	更新失败!	{"error": "ERROR: column \"chart_style_option = ?\" of relation \"chart_saveds\" does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/06/07 - 13:19:18.295	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:63	更新失败!	{"error": "ERROR: column \"chart_style_option = ?\" of relation \"chart_saveds\" does not exist (SQLSTATE 42703)"}
[github.com/lhxlnsy/pap-go-server]2022/06/07 - 13:22:12.609	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/06/13 - 13:19:04.406	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/06/15 - 13:00:16.337	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:361	获取失败	{"error": "ERROR: zero-length delimited identifier at or near \"\"\"\" (SQLSTATE 42601)"}
[github.com/lhxlnsy/pap-go-server]2022/06/15 - 13:15:06.078	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:361	获取失败	{"error": "ERROR: zero-length delimited identifier at or near \"\"\"\" (SQLSTATE 42601)"}
[github.com/lhxlnsy/pap-go-server]2022/06/15 - 13:15:38.859	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:361	获取失败	{"error": "ERROR: zero-length delimited identifier at or near \"\"\"\" (SQLSTATE 42601)"}
[github.com/lhxlnsy/pap-go-server]2022/06/15 - 13:16:07.541	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:361	获取失败	{"error": "ERROR: zero-length delimited identifier at or near \"\"\"\" (SQLSTATE 42601)"}
[github.com/lhxlnsy/pap-go-server]2022/06/21 - 09:40:28.724	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:215	获取失败!	{"error": "ERROR: could not load library \"/usr/lib/postgresql/timescaledb-2.6.0.so\": /usr/lib/postgresql/timescaledb-2.6.0.so: undefined symbol: ExecGetUpdateNewTuple (SQLSTATE XX000)"}
[github.com/lhxlnsy/pap-go-server]2022/06/21 - 09:40:51.011	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:215	获取失败!	{"error": "ERROR: could not load library \"/usr/lib/postgresql/timescaledb-2.6.0.so\": /usr/lib/postgresql/timescaledb-2.6.0.so: undefined symbol: ExecGetUpdateNewTuple (SQLSTATE XX000)"}
[github.com/lhxlnsy/pap-go-server]2022/06/21 - 09:40:56.102	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:215	获取失败!	{"error": "ERROR: could not load library \"/usr/lib/postgresql/timescaledb-2.6.0.so\": /usr/lib/postgresql/timescaledb-2.6.0.so: undefined symbol: ExecGetUpdateNewTuple (SQLSTATE XX000)"}
[github.com/lhxlnsy/pap-go-server]2022/06/21 - 09:43:17.552	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/06/21 - 09:43:33.540	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/pap/pap_siteinfor.go:215	获取失败!	{"error": "ERROR: could not load library \"/usr/lib/postgresql/timescaledb-2.6.0.so\": /usr/lib/postgresql/timescaledb-2.6.0.so: undefined symbol: ExecGetUpdateNewTuple (SQLSTATE 58P01)"}
[github.com/lhxlnsy/pap-go-server]2022/06/27 - 11:37:15.494	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	net.Listen error: listen tcp :8888: bind: address already in use
[github.com/lhxlnsy/pap-go-server]2022/06/27 - 11:37:48.712	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/07/04 - 12:39:36.886	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/07/28 - 12:32:09.241	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/07/28 - 12:46:32.136	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/07/28 - 12:55:32.697	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/07/28 - 12:55:38.407	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/07/28 - 12:55:54.604	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/system/sys_menu.go:27	获取失败!	{"error": "ERROR: relation \"authority_menu\" does not exist (SQLSTATE 42P01)"}
[github.com/lhxlnsy/pap-go-server]2022/08/02 - 11:27:19.581	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/08/02 - 11:27:58.430	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/08/02 - 11:30:20.621	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/08/03 - 12:10:46.704	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/08/22 - 13:37:29.157	[31merror[0m	/mnt/data2/Project/pap-go-server/api/v1/system/sys_user.go:47	登陆失败! 用户名不存在或者密码错误!	{"error": "record not found"}
[github.com/lhxlnsy/pap-go-server]2022/09/05 - 11:39:21.043	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/09/05 - 11:42:19.219	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/09/05 - 12:51:08.148	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/09/05 - 13:08:04.741	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/09/05 - 13:20:53.317	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
[github.com/lhxlnsy/pap-go-server]2022/09/05 - 13:25:43.701	[31merror[0m	/mnt/data2/Project/pap-go-server/core/server.go:42	accept tcp [::]:8888: use of closed network connection
